spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

openai:
  secret: ${OPENAI_SECRET}

email:
  mailgun:
    from-email: SmartTODO <noreply@smarttodo.org>
    username: api
    password: key-smt
    frontend-url: 'https://localhost:3000/'
    frontend-reset-password-url: 'https://localhost:3000/'