name: Deploy to Render

on:
  release:
    types: [published] # Trigger the workflow when a release is published
  push:
    tags:
      - 'v*' # Trigger the workflow for tags starting with 'v'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Render CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh

      - name: Set Render Workspace
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render workspace set aitodo-workspace -o json

      - name: Get Commit SHA
        id: git-info
        run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Verify Render CLI Installation
        run: render --version

      - name: Update Environment Variables on Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render env add ${{ secrets.RENDER_SERVICE_ID }} DB_URL="${{ secrets.DB_URL }}" --confirm
          render env add ${{ secrets.RENDER_SERVICE_ID }} DB_USERNAME="${{ secrets.DB_USERNAME }}" --confirm
          render env add ${{ secrets.RENDER_SERVICE_ID }} DB_PASSWORD="${{ secrets.DB_PASSWORD }}" --confirm
          render env add ${{ secrets.RENDER_SERVICE_ID }} OPENAI_SECRET="${{ secrets.OPENAI_SECRET }}" --confirm

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploys create ${{ secrets.RENDER_SERVICE_ID }} --commit ${{ env.commit }}