name: Deploy to Render

on:
  release:
    types: [published] # Trigger the workflow when a release is published
  push:
    tags:
      - 'v*' # Trigger the workflow for tags starting with 'v'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Render CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh

      - name: Set Render Workspace
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render workspace set aitodo-workspace -o json

      - name: Get Commit SHA
        id: git-info
        run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Verify Render CLI Installation
        run: render --version

      - name: Set Environment Variables for Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render services update-environment ${{ secrets.RENDER_SERVICE_ID }} \
          --env-vars "DB_URL=${{ secrets.DB_URL }}" \
                     "DB_USERNAME=${{ secrets.DB_USERNAME }}" \
                     "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
                     "OPENAI_SECRET=${{ secrets.OPENAI_SECRET }}"

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploys create ${{ secrets.RENDER_SERVICE_ID }} --commit ${{ env.commit }}
