name: Deploy to Render

on:
  release:
    types: [published] # Trigger the workflow when a release is published
  push:
    tags:
      - 'v*' # Trigger the workflow for tags starting with 'v'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Render CLI
      - name: Install Render CLI
        run: |
          curl -fsSL https://github.com/renderinc/render-cli/releases/latest/download/install.sh | bash
          echo "$HOME/.render/bin" >> $GITHUB_PATH
          export PATH="$HOME/.render/bin:$PATH"

      # Step 3: Verify Render CLI installation
      - name: Verify Render CLI Installation
        run: |
          which render
          render --version

      # Step 4: Deploy the application to Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} # Render API Key from GitHub secrets
        run: render deploy --service ${{ secrets.RENDER_SERVICE_ID }} --branch ${{ github.ref_name }}